apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skywright-backend
  labels:
    app.kubernetes.io/name: skywright-backend
    app.kubernetes.io/part-of: skywright
spec:
  ingressClassName: contour
  rules:
    - host: skywright.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skywright-backend
                port:
                  name: http
