apiVersion: apps/v1
kind: Deployment
metadata:
  name: skywright-skypilot-api-server
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-skypilot-database
          env:
            - name: SKYPILOT_DB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: skywright-production-skypilot-database
                  key: connectionUri
      containers:
        - name: skypilot-api-server
          env:
            - name: SKYPILOT_DB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: skywright-production-skypilot-database
                  key: connectionUri
