version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      maven:
        patterns:
          - '*'
        exclude-patterns:
          - 'org.springframework*'
          - 'org.springframework.boot*'

  - package-ecosystem: pip
    directory: /sdk
    schedule:
      interval: weekly
    groups:
      python-uv:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      pnpm:
        patterns:
          - '*'
        exclude-patterns:
          - '@angular/*'
          - 'rxjs'
