apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: skywright
resources:
  - ../../base
  - postgresql-config.yaml
  - postgresql-deployment.yaml
patches:
  - path: backend-patch.yaml
  - path: skypilot-api-server-patch.yaml
