# Generated by scripts/generate-run-definition-models from sdk/src/skywright/_run_definition_resources/schema.json. Do not edit.
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from skywright._run_definition_codec import (
    RunDefinitionValidationError,
    copy_value,
    decode,
    encode,
)

__all__ = ["RunDefinition", "RunDefinitionValidationError"]


@dataclass(frozen=True, init=False)
class RunDefinition:
    """Immutable internal model generated for Run Definition schema version 1."""

    _value: dict[str, Any]

    @classmethod
    def decode(cls, document: str) -> RunDefinition:
        definition = object.__new__(cls)
        object.__setattr__(definition, "_value", decode(document))
        return definition

    def to_json(self) -> str:
        return encode(self._value)

    def value(self) -> dict[str, Any]:
        return copy_value(self._value)
