apiVersion: v1
kind: Service
metadata:
  name: skywright-backend
  labels:
    app.kubernetes.io/name: skywright-backend
    app.kubernetes.io/part-of: skywright
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: skywright-backend
  ports:
    - name: http
      port: 80
      targetPort: http
