apiVersion: v1
kind: Service
metadata:
  name: skywright-skypilot-api-server
  labels:
    app.kubernetes.io/name: skywright-skypilot-api-server
    app.kubernetes.io/part-of: skywright
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: skywright-skypilot-api-server
  ports:
    - name: http
      port: 46580
      targetPort: http
