// Generated by scripts/generate-run-definition-models from sdk/src/skywright/_run_definition_resources/schema.json. Do not edit.
package de.zorro909.skywright.backend.rundefinition;

import javax.annotation.processing.Generated;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.node.ObjectNode;

/** Immutable internal model supporting Run Definition schema versions 1 and 2. */
@Generated("scripts/generate-run-definition-models")
public final class RunDefinition {

	private final ObjectNode value;

	private RunDefinition(ObjectNode value) {
		this.value = value.deepCopy();
	}

	public static RunDefinition decode(String document) {
		return new RunDefinition(RunDefinitionCodec.decode(document));
	}

	public static RunDefinition from(JsonNode value) {
		return decode(value.toString());
	}

	public ObjectNode value() {
		return this.value.deepCopy();
	}

	public String manifestArtifactDigest() {
		return this.value.at("/trainingProjectVersion/manifestArtifactDigest").asText();
	}

	public JsonNode configuration() {
		return this.value.path("configuration").deepCopy();
	}

	public JsonNode datasetDefinition() {
		return this.value.path("datasetDefinition").deepCopy();
	}

	public String encode() {
		return this.value.toString();
	}

	@Override
	public boolean equals(Object other) {
		return other instanceof RunDefinition definition && this.value.equals(definition.value);
	}

	@Override
	public int hashCode() {
		return this.value.hashCode();
	}

}
