package de.zorro909.skywright.backend.datasetpublication;

enum DatasetPublicationState {

	AWAITING_UPLOAD, UPLOADING, VERIFYING, COMMITTING, ABORTING, ABORTED, PUBLISHED_CLEANUP_PENDING, COMMITTED, FAILED,
	FAILED_CLEANUP

}
